import React from "react";
import Navbar from "../../NavBar/Navbar";
import DesktopFooter from "../../Footer/footer";
import './TermsAndContion.css'

class TermsAndCondition extends React.Component{

    componentDidMount(){
        let self = this
        window.onscroll = function() {self.scrollFunction()};
    }

    scrollFunction(){

        var mybutton = document.getElementById("back-top");

        if(mybutton){
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

    }
    topFunction(){
        document.body.scrollTop = 0;
        // document.documentElement.scrollTop = 0;
        window.scrollTo({top: 0, behavior: 'smooth'});
    }

    render(){
        return(

            <div style={{backgroundColor: '#f2f2f2'}}>

                <Navbar />
                <div className="desktopTermsCondition">
                <h1 className="page-title">
                    <span className="base" data-ui-id="page-title-wrapper">Terms &amp; Conditions</span></h1>
                    <div className="desktopTermsConditionMain">
                <div className="page-title-wrapper"><span style={{fontSize: 'large'}}><strong>Privacy Policy</strong></span></div>
                <div className="column-terms">
                    <div className="column main">
                        <p><span style={{fontSize: 'medium'}}><strong /></span></p>
                        <p><span style={{fontSize: 'medium'}}><strong /></span></p>
                        <p>ITC Limited respects an individual’s right to privacy. This policy lays down its practices with respect to confidentiality and disclosure of personal information. Please familiarize yourself with its privacy practices, as given below. Should you choose to share your personal information, it will be assumed that you have no objection to the terms of this privacy policy.</p>
                        <p>This Privacy Policy covers the information collected, processed, accessed, stored and controlled by <span>ITC Limited</span> either by itself or through its third party vendors (hereinafter referred to as <span>‘ITC’</span>) from the user(s) (<span>“User(s)”</span> and/or <span>“You”</span>) of <span>classmateshop.com (“Website”)</span> and/or the Services provided by ITC on the Website (as defined in the Terms of Use of the Website – <span>“Terms of Use”</span>), which Services can be used or accessed on the Website (as defined in the Terms of Use).</p>
                        <p>ITC has also adopted reasonable security practices and procedures comprising of managerial, technical, operational and physical security control measures with a view to ensure confidentiality and prevent unauthorized disclosure of personal information. ITC uses the personal information only for the purpose for which the same has been furnished. ITC does not retain information after the purpose for which it is furnished is accomplished unless the same is required to be retained under any law in force or for audit purposes. In such cases also, confidentiality of such information is maintained.</p>
                        <p>This Privacy Policy should be read in conjunction and together with the Terms of Use available on the Website. Personal Information of a User(s) is collected if the User(s) registers with the Website, accesses the Website or takes any action on the Website or uses or accesses the Services as defined in the Terms of Use. The terms ‘Personal Information’, ‘Sensitive Personal Data’ and ‘Information’ shall have the meaning ascribed to it under the Information Technology Act, 2000 and rules therein. Your use of its services offered on the Website is constructed to mean that You consent to its collection, storage, processing and transfer of your Personal Information or Sensitive Personal Data or Information in accordance with this Privacy Policy and You consent to the terms and conditions of this Privacy Policy. ITC shall not be responsible in any manner whatsoever for any violation or misuse of your personal information by unauthorised persons consequent to misuse of the internet environment.</p>
                        <p>Here are its privacy principles:</p>
                        <p><span>1. Collection of Information And Use</span></p>
                        <p>The Personal Information or Sensitive Personal Data or Information which You may provide ITC and/or which ITC may collect as part of the information provided is or could be the following:</p>
                        <p>Your Registration Details Which May Include The Name, Email Address, Mobile/Contact Details, Password, Location, Pin Code, Area Code, Provided By You, Content That You Publicly Upload Or Share On The Website. If You Access Or Engage With The Website Or Services Associated With The Website Through A Social Media Service, ITC May Collect Your User ID Or User Name, Any Information You Have Permitted The Social Media Service To Share With Us, And Any Information You Have Made Public With The Social Media Service. Your Billing, And Other Information Pertaining To Your Transactions On The Website Or Related To The Services.; Your Usage Behavior Of The Website Or Interests, , Other Traceable Activities Online, On Apps And On Mobile Such As Destinations Visited, Viewed Advertisements Or Content Consumed. Details Of The computer operating System Or computer operating Network Which You Use To Visit The Website And Undertake Any Activity On The Website , Such As A Unique Device Identifier including user behaviour from web based cookies Session Identifiers From Device ID, Commercially Available Services, Data Aggregator Platforms. User Preferences (E.G., Preferred Language Settings); IP Address, IP Address, Operating System, Browser Type, Browser Version, Browser Configuration, Name Of Internet Service Provider, And Other Types Of Computer And Connection Related Information Relevant To Identifying Your Type Of Device, Connecting To The Website, Enabling Data Exchange With You And Your Device, And Ensuring A Convenient Use Of The Website; The Uniform Resource Locator (URL) And IP Address Of The Website From Which You Accessed, Or Were Directed To, The Website, Including Date And Time;Subpages Visited While On The Website, Links Followed On The Website, Including Date And Time;The Full URL Click Stream To, Through And From The Website, Including Date And Time;Service Requests and Orders Placed; Transaction History, Including Open and Completed Transactions; Search Terms Entered;Services Viewed Or Searched For On The Website;;Information Collected By Cookies Or Similar Technologies (As Described In The Next Paragraph); Shopping Cart And Payment Information; Credit Card Information;, Enrollment For Promotions, Use Of Special Offers, Etc. Consents, Authorizations, Etc. Granted; Survey Answers, Reviews, Ratings And Other Types Of Feedback Provided; Content Of Any Communication Sent Through The Website,; Information On Software Downloaded From The Website; And Any Other Information That You Enter On, Or Upload To, The Website (E.G., Content That You Fill Into An Online Form, A Photo That You Upload).</p>
                        <p>If You contact ITC in regard to technical support, questions about your order, or any general inquiry, your email address will only be used in response to your inquiry.</p>
                        <p>ITC may collect information covering your name, address, addresses. In addition, ITC may collect information about You from third parties for verification, credit worthiness, payment history, address verification. ITC may also collect information from your visits to its other websites and associates including pages visited on the ITC’s other websites, your website visit pattern and purchase pattern. In addition, ITC may obtain information about You from public sources.</p>
                        <p>Our primary purposes in collecting information including Personal Information or Sensitive Personal Data or Information from You is to allow You to use the Website and various features and Services on or in relation to the Website or any Sites contact You for any Services provided by ITC; to record Your information and details as permitted and required under applicable laws, statutory direction or judicial orders; to serve various promotion materials and advertising materials to You; and such other uses as provided in the Terms of Use and this Privacy Policy. ITC may also use the Personal Information or Sensitive Personal Data, or Information provided by You or collected by ITC for content recommendations, transactional emails or to provide You with information, direct marketing, online and offline advertising and other materials regarding products, services and other offers from time to time.</p>
                        <p>ITC may also collect information or Personal Information to track User behaviour and preferences for internal analytics of all Users of the Website. ITC may also use your information: (i) to evaluate your eligibility for certain types of offers, products or services; (ii) to perform analytics and conduct customer research, including general market research or surveying its customers' needs and opinions on specific issues, generating sales and traffic patterns, and to analyze advertising effectiveness, both on an anonymous basis (e.g., by aggregating data) or on an individual basis (if legally permissible);</p>
                        <p>This Personal Information or Sensitive Personal Data or Information is collected through the use of server log files and tracking technologies to collect and analyze certain types of technical information and may include cookies and web beacons. If You do not consent to the use of cookies and/or device session tracking by the Platform, You may at any time adjust Your browser settings and/or delete and/or disable the cookies. However, please note that should You choose to delete/ disable the use of cookies or other tracking technologies on Your computer, certain sections of the Website and/or Services provided by ITC may not be available to You. You can stop all collection of information by the Website easily by deleting your Account and exiting the website.</p>
                        <p>The list of types of information that ITC collects may change from time to time and ITC reserves the right to collect this information where it is related to its business with You or its potential business with You. ITC may use technology available from time to time to help ITC with analysis and decision making.</p>
                        <p>You understand, agree and acknowledge that its collection, storage and processing of your Personal Information or Sensitive Personal Data or Information is for a lawful purpose connected with your use of the Website. You hereby consent to the collection, storage, use, disclosure, transfer, of the Personal Information or Sensitive Personal Data or Information by ITC for the purposes set out herein. You further understand, agree and acknowledge that Your Personal Information which is classified as Sensitive Personal Data or Information as per applicable laws is considered necessary for ITC to provide various services on its Website to You and for Your usage of the Website and other services provided by ITC in relation to the Website and You affirmatively consent to its collection, storage, transfer and processing.</p>
                        <p><span>2. Information Sharing and Disclosure</span></p>
                        <p>ITC is the recipient of Your Personal Information or Sensitive Personal Data or Information and shall exercise reasonable commercial endeavours for the prevention of unauthorized disclosure of the Personal Information including any Sensitive Personal Data or Information provided by the Users. ITC may enable access of Your Personal Information or Sensitive Personal Data or Information to the third parties service providers for the purposes of the services provided by them or for any other marketing related activity undertaken by or on behalf of ITC, and/or for the purposes of enhancing the quality of the services provided to You on the Website, and You expressly consent to the same.</p>
                        <p>ITC may share contact information and your order information with other units within its group company websites, and respectable third parties. ITC may also share your information with third party vendors (such as a courier service providers) who will be authorised to use this information solely to perform services on its behalf.</p>
                        <p>ITC shall endeavour that the third parties and agents engaged by ITC to whom ITC may provide access to Your Personal Information or Sensitive Personal Data or Information for the purposes set out herein are under a contractual obligation to protect Your Personal Information or Sensitive Personal Data or Information in accordance with the same standard as ITC has agreed to be subject to in this Privacy Policy.</p>
                        <p>ITC may disclose Your Personal Information or Sensitive Personal Data or Information to such extent as the Platform may deem necessary for You to enter into commercial transactions with the Website.</p>
                        <p><span>3. Compliance With Laws And Law Enforcement</span></p>
                        <p>ITC cooperates with mandated government and law enforcement agencies or to any third parties by an order under law for the time being in force to enforce and comply with the law. ITC will also disclose any information including Sensitive Personal Data or Information about You to government and law enforcement agencies without your permission as we, in its sole discretion, believe necessary or appropriate to respond to valid claims and legal process, to protect the property and rights of ITC or a third party vendors or service providers, to protect the safety of the public or any person, or to prevent or stop any illegal, unethical or legally actionable activity. ITC may also provide Your Personal Information including Sensitive Personal Data or Information to various governmental authorities including tax authorities upon any demand or request from them.</p>
                        <p><span>4. Email and SMS Policies</span></p>
                        <p>ITC may use Your Personal Information or Sensitive Personal Data or Information for the purposes mentioned in this Privacy Policy. You have full control regarding which emails You want to receive. If You decide at any time that You no longer wish to receive such communications from ITC , please follow the unsubscribe instructions provided in any of the communications. Please note that once ITC receives Your request, it may take an additional period of time for Your opt-out to become effective.</p>
                        <p>The use of this information is purely for the use of conducting the transaction for marketing purposes. This includes sending You email messages, SMS, MMS (Text Messages using mobile cellular technology, telephone calls, letters and other communication). ITC may share this information with its marketing partners, consultants and third parties for the purpose of making special offers to You as its customer. ITC may also call You on the telephone and as an existing customer, and will not specifically refer to the “Do Not Call Registry” for this purpose. By purchasing Products from the Website, You are deemed to be its customer and ITC may contact You on phone, email, to conduct its business with You or to resolve matters related to its business with You.</p>
                        <p>From time to time, ITC may send You information about new products, features, additions, and changes to products and services being sold on the Website.</p>
                        <p><span>5. Data Security</span></p>
                        <p>ITC understands the importance of data security and ITC want your user experience with ITC to be as safe as possible. ITC has implemented reasonable safeguards and precautions to protect Your Personal Information or Sensitive Personal Data or Information, including technical and organizational measures against unauthorized access, improper use, alteration, unlawful or accidental destruction, and accidental loss.</p>
                        <p>ITC has adopted reasonable security practices and procedure and ITC maintains technical and organizational security measures and procedures to protect the security of your Your Personal Information or Sensitive Personal Data or Information, which are consistent with measures used by other similar Websites. However, in the event of any loss of data by the third parties is not its liability and if such an occurrence happens ITC will inform You via your registered email address within 48 hours of ITC being notified.</p>
                        <p>Please understand that, while ITC strives to protect Your Personal Information or Sensitive Personal Data or Information against potential risks and exposures, there is no absolute security in the online sphere. Hence, ITC asks You to support its IT security efforts by not disclosing any of Your Personal Information or Sensitive Personal Data or Information data on its Website that is particularly sensitive or not required in the specific context. Furthermore, You can help ITC in protecting your personal data by signing off when You finish using login-protected areas of the Website.</p>
                        <p><span>6. Data Retention</span></p>
                        <p>ITC retains Personal Information or Sensitive Personal Data or Information only for as long as ITC believes it to be necessary for purposes set out herein for which the Personal Information or Sensitive Personal Data or Information was collected, subject to any legal requirements for the data to be retained for longer periods of time.</p>
                        <p><span>7. Deleting Your Information</span></p>
                        <p>If You wish to have the Personal Information or Sensitive Personal Data or Information that You have provided to ITC deleted, You can always do so by sending a request to ITC on the e-mail id of its Customer Services department provided at the bottom of this page. You may note that deletion of certain Personal Information may lead to cancellation of your registration with the Website and/or your access to certain features of the Website can be restricted and may also lead to complete cessation of Your Access to the Website.</p>
                        <p><span>8. Links To Other Sites / Financial Data</span></p>
                        <p>ITC provide links to other websites and portals for your convenience and information (“Other websites”). For instance, the ITC will be using third party payment gateway providers to process and facilitate the payment for your orders made on the Website for providing You access to the payment facility. Please note that ITC does not directly collect any Financial information such as Credit Card or Debit Card or Net Banking details from You. Such Other websites are not controlled by us. When You visit such Other website You do so at your own risk. These Other websites may have their own privacy policies in place, which ITC recommend You review if You visit any such Other websites. ITC do not assume any responsibility or liability for such Other websites, the content of such Other websites and their privacy practices, nor do ITC endorse them. ITC encourages You to familiarize yourself with the privacy statements provided by such Other websites prior to providing them with information about You or entering into any transactions on them.</p>
                        <p>While transacting with these Other websites, You may provide Your financial information including without limitation Your bank account details, credit card account details or your details pertaining to any payment settlement or pre-paid instrument service provider. You understand, agree and acknowledge that the Website and ITC never receives any such information from these Other websites. Your Personal Information, Sensitive Personal Data or Information and financial information will be dealt with by these Other websites in accordance with their respective privacy policies and other terms and conditions and the ITC shall not be liable, accountable or responsible for Your Personal Information, Sensitive Personal Data or Information and financial information which You provide to these Other websites.</p>
                        <p><span>9. Security</span></p>
                        <p>ITC uses commercially reasonable security practices and procedures industry practices and procedures designed to help keep Your Personal Information or Sensitive Personal Data or Information safe. Secure server software (SSL) encrypts all information You submit before it is sent to us. Furthermore, all of the User data ITC collects is protected against unauthorized access. To prevent unauthorized access, maintain data accuracy, and ensure correct use of information, ITC will employ commercially reasonable and practicable security practices and procedures and security methods and technologies. ITC will also ensure on reasonable commercial efforts basis that any agent or third party that ITC employs complies with the same security standards as ITC does for the protection of your Personal Information or Sensitive Personal Data or Information. For example, ITC limits access to this information to authorized employees and contractors who need to know that information in order to operate, develop or improve the Website.</p>
                        <p>Your information may be transferred to or may be maintained on computers, computer systems and computer resources located outside of Your state where the privacy laws may be different as those where You live. If You are located outside India and choose to provide information to us, please be aware that the Website is hosted in India and that ITC keeps or transfers information to and from India for storage and processing. Your submission of such information represents your agreement to that transfer.</p>
                        <p>Unfortunately, the transmission of information over the Internet is not completely secure. Although ITC strives to protect your personal data, ITC cannot guarantee the security of your data while it is being transmitted to the Website; any transmission is at your own risk. Once ITC has received your information, ITC has commercially reasonable procedures and security practices in place to reasonably endeavour to prevent unauthorized access.</p>
                        <p><span>10. Changes In Privacy Policy</span></p>
                        <p>ITC reserves its right to revise this privacy policy from time to time at its sole discretion. Such policy will be available on the Website.</p>
                        <p>Your continued use of the Website and the Services constitutes Your acceptance of the then-current Privacy Policy and Terms of Use so ITC encourages You to visit this page periodically to review any changes.</p>
                        <p><span>11. Phishing</span></p>
                        <p>Identity theft and the practice currently known as "phishing" are of great concern to us. Safeguarding information to help protect You from identity theft is a top priority. ITC does not and will not, at any time, request Your credit card information or national identification numbers in a non-secure or unsolicited e-mail or telephone communication.</p>
                        <p><span>12. Contact Us</span></p>
                        <p>If You have any questions about this Privacy Policy, its practices or Your dealings with the Website, You can contact ITC at or via the links at the bottom of the page. Email id: <span><a href="mailto:customer-care@classmateshop.com">customer-care@classmateshop.com</a></span></p>
                        <p><span>13. Grievance Officer</span></p>
                        <p>In accordance with the Information Technology Act, 2000 and the Rules framed thereunder, the name and contact details of the Grievance Officer are provided below:-</p>
                        <p>Quality Manager, Education and Stationery Businesses, ITC, 5th Floor, ITC Centre, 760, Anna Salai, Chennai – 600 002</p>
                        <p>Email id: <span><a href="mailto:customer-care@classmateshop.com">customer-care@classmateshop.com</a></span></p>
                        <p>Phone no.: 18004253242</p>
                        <p>9 AM to 5 PM (on all working days)</p>
                        <p>If You have any questions or grievance or want to delete or modify Your Personal Information, You shall mark Your correspondence (given under the heading “About Us”). Any communication which is not marked as such shall not be treated as a valid and binding communication for the purpose of this Privacy Policy and applicable laws with respect to this Privacy Policy.</p>
                        <h3><span style={{fontSize: 'medium'}}>TERMS OF USE- CLASSMATESHOP.COM</span></h3>
                        <p>This page states the Terms and Conditions under which you ( hereinafter referred to as You or User) may use this classmateshop.com website (hereinafter referred to as the 'Website'). Please read this page carefully. If You do not accept the Terms and Conditions stated here, You may exit this Website.</p>
                        <p>The Website is operated by Wewin Paper Products (hereinafter referred to as ‘Wewin’) Wewin is a partnership firm under the Indian Partnerships Act of 1923 having its principal place of business at Survey No. 217, Kandlakoya Village, Ayodhya Centre, Medchal Mandal, RR District – 501401, Telangana. The brand/ trademark ‘Classmate’ belongs to ITC Limited and is being used on this website under a specific agreement. ITC Limited is a company within the meaning of Companies Act, 2013, having its registered office at 37, Jawahar Lal Nehru Road, Kolkata – 700 071(.hereinafter referred to as ITC). ITC owns the Website and shall retain all intellectual property rights, ownership and proprietary rights and shall have the sole right, title and interest in and over the Website. Wewin has neither the ownership nor any authority over the ‘Classmate’ Trademark.</p>
                        <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and various other statutes. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <p>This is a legal and binding agreement between You, Wewin and ITC stating the terms that govern Your use of the Website, as defined below. By accepting these terms of use in any manner or accessing this website, You consent, agree and undertake to abide, be bound by and adhere to the terms of use and the Privacy Policy accessible at the website, respectively and any other terms which govern the website (together referred to as “Terms of Use” or “Terms” or “Terms and Conditions”) and if You do not agree to these terms of use, You are not entitled to avail of / use the Services (defined below) and any use thereafter shall be unauthorized. By using this Website You declare and agree that You have the full power and authority to make and enter into a transaction with Wewin and ITC and that You are over 18 years of age and are legally competent to enter into an agreement.</p>
                        <p>If You wish to not be bound by these terms of use You may do so by (a) closing Your account on the Website and (b) exit the Website. ITC has made this option available to You.</p>
                        <p><span>Description of Service and Acceptance of Terms of Use</span></p>
                        <p>ITC inter alia provides the Website for its users to inter alia customize and purchase Classmate Exercise books (hereinafter referred to as the “Products”) on the Website using any other features, tools, materials, or other services offered from time to time by ITC in connection with its business, provided on the website (hereinafter referred to as the “Content”) and includes posting of images by ITC on the Website(all such features of the website collectively referred to as “Services”). The Products can be purchased through the website through various methods of payments offered. The use of the website and sale/purchase of Products shall be governed by the terms mention in this document. Content will be made available to You on the website and You may also upload some material (hereinafter referred to as ‘User Material’ more fully described in the later part of the document) on the Website. You will be granted a non-exclusive, non-transferable, non-sublicensable revocable limited permission to use the Content (except the User Material uploaded by You) for your personal, non-commercial using, and that no right, title or interest in any Content will be deemed transferred to You. No part of the website, the designs or the terms and references within shall be copied or transmitted for commercial purposes. Nothing contained herein shall grant or be deemed to grant, whether directly or by implication, You any right, title or interest in or to the ownership or use of the Trade Marks and Intellectual property. Purchases of products on this site does not transfer any of the intellectual property related to the products, their design or concepts to You.</p>
                        <p><span>Contract</span></p>
                        <p>You agree that by placing an order with Wewin,You are the purchaser of the Products and Wewin is the seller. Wewin sells the Products and collects the payment from You. ITC has provided the Website for Wewin to sell the Products under the brand name of ‘Classmate’; a trademark and brand owned by ITC.</p>
                        <p>You agree and understand that your order is an offer to Wewin to buy the product(s) in your order. When your order number is generated after making payment through the payment gateway, You will receive an e-mail and sms confirming receipt of your order and containing the details of your order (the "Order Confirmation E-mail"), this is acceptance of the offer made by You to purchase the Products. It is here that agreement to sell is complete.</p>
                        <p>When your order is dispatched to the third-party courier service provider, You will receive a separate Dispatch Confirmation E-mail, and on confirmation of delivery by our Logistics partner, You shall receive an email confirming the same, at this stage title in the Product passes on to You. However, the risk in the Product shall remain with Wewin until the Product is delivered to You at your shipping address. You have the right to examine the Products delivered to You, it will be deemed to have accepted the Products if not return to Wewin within 7 days of the receipt of the Product at the shipping address. For delivery policy and return policy see below.</p>
                        <p>You agree and acknowledge that the Product(s) ordered by you are purchased for your personal purpose and not for re-sale or commercial activity. You authorize Wewin and ITC to declare and provide declaration to any governmental authority on your behalf stating the aforesaid purpose of the products ordered by You on the Website.</p>
                        <p>Please note that the availability of, and Your ability to access, the Content or some part of Services, (a) is subject to ITC’s sole discretion and (You hereby agree and acknowledge that You are accessing this Website and availing of the Services, at Your own risk, choice and initiative and You agree and undertake to ensure that Your use of the Website and the Services complies with all applicable laws in India including the local laws in Your jurisdiction. Further, such Services and Content may be subject to various parameters such as specifications, device, Internet availability and speed, bandwidth, etc.</p>
                        <p>The Service can be availed through platforms, software and devices, which ITC approves from time to time, the current list for which is as set out below <span>(“Compatible System”)</span>. In some cases, whether a device is (or remains) a Compatible System may depend on software or platform provided or maintained by the device manufacturer or other third parties. As a result, devices that are Compatible System at one time may cease to be Compatible System in the future.</p>
                        <p>The Website works best when accessed from a Desktop browser, and with the following browsers</p>
                        <ul>
                            <li>Microsoft Edge</li>
                            <li>Mozilla Firefox</li>
                            <li>Google Chrome for Windows and Mac</li>
                            <li>Opera</li>
                            <li>Safari</li>
                        </ul>
                        <p>Please see details on the Website and the particular Content used. Subject to compatibility, You may be able to access the Services including Content through mobile phones, tablets and other IP based connected devices or any Compatible System offered by a partner authorized by ITC. Customisation of exercise books best happens on desktop browser, and when accessed through a phone, tablet or any other device, not all features or none of the features may function optimally.</p>
                        <p>Use of the Services is subject to compliance with these Terms of Use.</p>
                        <p>Your access to and use of the Services is subject to these Terms and Conditions, Privacy Policy and all applicable laws, rules, and regulations.</p>
                        <p>Participation in any contest and or game on the Website conducted by ITC or using of certain Content may be subject to further terms and conditions as may be notified by ITC from time to time on the Website or otherwise.</p>
                        <p><span>Electronic Communications</span></p>
                        <p>When You use/avail the Services or send any data, information or communication to ITC, You agree and understand that You are communicating with ITC. ITC will communicate with You by email or any push or other message or electronic records on the email address and or mobile number available with ITC or made available to ITC through a partner which will be deemed adequate service of notice / electronic record.</p>
                        <p>You acknowledge specifically to giving consent to ITC and Wewin or respective affiliates contacting You using the contact information You have provided to us at any time during your association with us for any purpose including the following purposes:</p>
                        <p>To communicate details of the placed order – order confirmation or failure, order shipment details and/or order delivery details.</p>
                        <p>To obtain feedback regarding the Service; To contact You for offering new products or services, whether offered by us, or our respective affiliates or partners.</p>
                        <p>You acknowledge and agree that You may be contacted for the above purposes, using any of the contact details provided by You, including via emails, text messages or phone calls.</p>
                        <p>In the event You have indicated any ‘do not disturb’ preferences to your telecom service provider and registered yourself on the national customer preference register / ‘do not disturb’ or similar list, It is requested that You ensure that your registered preferences allow for communications to be sent to You in accordance with the above provisions.</p>
                        <p>The Content contained in the Services including but not limited to on the Website is protected by copyright, trademark, patent, trade secret and other laws, and shall not be used except as provided herein.</p>
                        <p><span>Access and Use of the Services</span></p>
                        <p>ITC grants You a non-exclusive limited, revocable, limited permission to use the Services on the Website for personal, non-commercial purposes during and after the subsistence of your Account with ITC or Partner for the territory of the world or limited territories as applicable in respect of specified Content and as set forth in these Terms and Conditions.</p>
                        <p>By agreeing to use/avail the Services:</p>
                        <p>You confirm and warrant that all the data and information supplied by You when You register and provided by You to ITC and Wewin or any ITC or Wewin’s affiliates, distributors (“Registration Data”) is true, current, complete and accurate in all respects. The Website permits and requires You to create an account to access the Website and the Services offered in the Website, to access history of your previous transactions, additional content, or to secure additional benefits. You may have to be registered and provide your name, email address and other details to create an account using the Services offered in the Website. You agree to promptly update your Registration Data, so that your information remains true, current, complete, and accurate at all times. You acknowledge and agree that your Registration Data and any other personal data collected by Wewin and ITC is subject to Classmateshop.com Privacy Policy. For more information, see the full Privacy Policy. You agree to only use your own account to access the Website and any Services offered. You shall not under any circumstances use the account, username, or password of someone else at the time of accessing the Website.</p>
                        <p>You acknowledge, consent and agree that Wewin and ITC may access, preserve, transfer and disclose your account information and/or User Material (see below) subject to the Privacy Policy, if required to do so by law to co-operate with mandated government and law enforcement agencies or to any private parties by an order under law for the time being in force to enforce and comply with the law including to various tax authorities upon any demand or request by them or in a good faith belief that such access, preservation, or disclosure is reasonably necessary to: (a) comply with legal process and/or any applicable law in the territory; (b) enforce the Terms and Conditions; (c) respond to your requests for customer service; or (d) protect the rights, property or personal safety of ITC and Wewin, affiliates, their users and the public. You agree that ITC has the right to temporarily suspend access to the whole or any part of the Services for any technical/operational reason and shall be under no liability to You in such an event. ITC may, but shall not be obliged to, give You as much notice of any interruption of access to the Services as is reasonably practicable. ITC will restore access to the Services as soon as reasonably practicable after temporary suspension. You agree that ITC shall be under no liability whatsoever to You in the event of non-availability of the Website or any portion thereof occasioned by Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, failure of any public utility, man-made disaster, satellite failure or any other cause whatsoever beyond the control of ITC.</p>
                        <p>You acknowledge and agree not to either directly or through the use of any device, software, app, web-based service, or other means remove, alter, bypass, avoid, interfere with, violate, or circumvent any patent; trade secret; copyright, trademark, or other proprietary notice marked on the Content or any digital rights management mechanism or device; any content protection or access control measure associated with the Content, including geo-filtering mechanisms; privacy; publicity; or other proprietary right under applicable law. You agree not to either directly or through the use of any device, software, internet app, web-based service, or other means copy, download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the Content or create any work or material that is derived from or based on the Content.</p>
                        <p>All logos, brands and marks appearing in this application, except as otherwise noted, are properties either owned, or used under licence, by ITC and / or its associate entities who feature on this application. The use of these properties or any other content on this application, except as provided in these terms and conditions or in the Website content, is strictly prohibited.</p>
                        <p>This prohibition applies regardless of whether such derivative works or materials are sold, bartered, or given away. You agree that ITC and/or its affiliates or licensors owns and/or retains all rights to the Services and the Content throughout the territory of the world in perpetuity. You further agree that the Content You access and use as part of the Services is owned or controlled by ITC, its affiliates and or its licensors. The Services and the Content are protected by copyright, trademark, design, patent, trade secret, and other intellectual property laws. Except as provided in these Terms (or otherwise expressly provided by ITC), You may not copy, download, stream capture, reproduce, duplicate, archive, upload, modify, translate, publish, broadcast, transmit, retransmit, distribute, perform, display, sell, frame or deep-link, make available, or otherwise use any Content contained in the Services.</p>
                        <p>You shall adhere to the legal rights and intellectual property rights of ITC and others when using the Website or its Services. You shall be solely responsible for violations of any relevant laws or infringement of intellectual property rights caused by any Content You provide or transmit, or that is provided or transmitted using your user account. The burden of proving that any Content does not violate any laws or third party rights rests solely with You. You shall not submit, post, upload, transmit, display, communicate, or otherwise distribute User Material in violation of any third party’s copyrights, patents, trademarks, trade secrets or other intellectual property or proprietary rights.</p>
                        <p>You further agree not to use the Services to Post, upload or otherwise transmit or link User Material that is: unlawful; threatening; abusive; obscene; vulgar; sexually explicit; pornographic or inclusive of nudity; hurts the religious sentiments of others; offensive; excessively violent; invasive of another’s privacy, publicity, contract or other rights; tortious; false or misleading; defamatory; libelous; hateful; or discriminatory; violates any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary right; or</p>
                        <ul>
                            <li>Harass or harm another person;</li>
                            <li>Exploit or endanger a minor;</li>
                            <li>Impersonate or attempt to impersonate any person or entity</li>
                            <li>Introduce or engage in activity that involves the use of viruses, software disabling codes, bots, worms, or any other computer code, files or programs that interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment, or otherwise permit the unauthorized use of or access to a computer or a computer network;</li>
                            <li>Attempt to decipher, decompile, disassemble or reverse engineer any of the software, applications and/or any element comprising the Website , the Website for accessing the Content, or the Services;</li>
                            <li>Interfere with, damage, disable, disrupt, impair, create an undue burden on, or gain unauthorized access to the Services, including ITC or Wewin’s servers, networks or accounts;</li>
                            <li>Cover, remove, disable, manipulate, block or obscure advertisements or other portions of the Services or the Content;</li>
                            <li>Delete or revise any information provided by or pertaining to any other user of the Services.</li>
                            <li>Use technology or any automated system such as scripts, spiders, offline readers or bots in order to collect or disseminate usernames, passwords, email addresses or other data from the ITC Services, or to circumvent, delete, deactivate, decompile, reverse engineer, disassemble or modify any security technology or software that is part of the ITC Services or the Website;</li>
                            <li>Send or cause to send (directly or indirectly) unsolicited bulk messages or other unsolicited bulk communications of any kind through the Services. If You do so, You acknowledge You will have caused substantial harm to ITC and Wewin, but that the amount of harm would be extremely difficult to measure in which case, ITC and Wewin retains the right to take appropriate legal recourse;</li>
                            <li>Solicit, collect or request any personal information for commercial or unlawful purposes;</li>
                            <li>Engage in commercial activity (including but not limited to advertisements or solicitations of business; sales; contests; sweepstakes; creating, recreating, distributing or advertising an index of any significant portion of the Content; or building a business using the Content) without ITC’s prior written consent;</li>
                            <li>Use technology or other means to access, index, frame, or link to the Website (including the Content) that is not authorized by ITC;</li>
                            <li>Access the Website /Service (including the Content) through any automated means, including “robots,” “spiders,” or “offline readers” (other than by individually performed searches on publicly accessible search engines for the sole purpose of, and solely to the extent necessary for, creating publicly available search indices – but not caches or archives – of the Website and excluding those search engines or indices that host, promote, or link primarily to infringing or unauthorized content);</li>
                            <li>Use the Services to advertise or promote competing services;</li>
                            <li>Use the Services in a manner inconsistent with any and all applicable law;</li>
                            <li>Attempt, facilitate, induce, aid and abet, or encourage others to do any of the foregoing.</li>
                        </ul>
                        <p>You are responsible for the security and proper use of your unique user ID and password that You enter while registering on the Website and must take all necessary steps to ensure that they are kept confidential, used properly, and not disclosed to unauthorized people. You agree that your use of the Services and the Content may give You the opportunity to use, publish, transmit, submit posts and/or comment in accordance with these Terms and Conditions. You agree that You will not misuse the Content and/or User Material. You will not access as part of the Service, including without limitation, download/store the Content by illegal/non-permitted means, or infringe any of ITC’s/ or its licensor’s copyright, trademark design, patent, and other intellectual property including any rights of ITC or its licensors subsisting in the Content. You further agree that You will not copy/record/edit/modify any of the Content You access and use as part of the Service, for any purpose, and/or copy/record/edit/modify any Content including images etc., by using any means including software, spyware, etc., for any purpose whatsoever. You further agree that You shall not post, publish, transfer, upload, transmit or submit any of the Content, including, of the Website on any other website, webpage or software, whatsoever which is not owned by ITC. You agree that the Content provided on the Website is strictly for your private using only and not for public exhibition irrespective of whether the public is charged for such exhibition or not. You hereby agree to refrain from further broadcasting or making available the Content provided on the Website to any other person(s), or in any manner communicate such Content to the public.</p>
                        <p>You agree that You will not use, sell, transfer or transmit the Content to any person or upload the Content on any other Website, webpage or software, which may violate/cause damages or injuries to any rights of ITC or its affiliates or any third-party including privacy rights, publicity rights, and intellectual property rights.</p>
                        <p>ITC reserves the right to immediately suspend or terminate the user account or use of the services of the User who is found to have infringed, or alleged to have infringed, on the rights of ITC or of a third party, or otherwise violated any intellectual property laws or regulations. You may please contact us if You have a good faith belief that your rights or the rights of a third party have been violated and You want ITC to delete, edit, or disable the User Material in question. You may be asked for providing additional information or proof of violation / infringement.</p>
                        <p>All contents of the Website are subject to Copyright © owned by ITC or license to ITC for use by the ITC and the You for the purposes of the Website. “Classmate”, “www.classmateshop.com”, the “Classmate logo” are intellectual property of ITC.</p>
                        <p><span>Termination of Service</span></p>
                        <p>ITC reserves the right to immediately terminate, suspend, limit, or restrict your account or your use of the Services or access to Content at any time, without notice or liability, if ITC so determines in its sole discretion, for any reason whatsoever, including that You have breached these Terms and Conditions, the Privacy Policy, violated any law, rule, or regulation, engaged in any inappropriate conduct, provided false or inaccurate information, or for any other reason. You hereby agree and consent to the above and agree and acknowledge that ITC can, at its sole discretion, exercise its right in relation to any or all of the above, and that ITC, its directors, officers, employees, affiliates, agents, contractors, principals or licensors shall not be liable in any manner for the same; and You hereby agree, acknowledge and consent to the same.</p>
                        <p><span>Deactivation of Your Account</span></p>
                        <p>You may also request deactivation of your <a href="http://www.classmateshop.com/" target="_blank" rel="noopener noreferrer">www.classmateshop.com</a> account by contacting Customer Care at 18004253242 or by sending an email to <a href="mailto:customer-support@classmateshop.co">customer-support@classmateshop.co</a> or writing to the address below and requesting account deactivation.</p>
                        <p>Quality Manager, ITC Ltd – ESPB, ITC Centre, 5th Floor, 760, Anna Salai, Chennai - 600002</p>
                        <p>Customization specifications</p>
                        <p>You agree and acknowledge that all files uploaded by You will be 300 DPI or vector format. The design should be sized accurately to the size of the exercise book You have selected (240 mm height X 180 mm width or 297 mm height X 210 mm width). The final design shall appear on the exercise book as it appears in the preview. You understand that printing can only be as good as the quality of the image uploaded. ITC and Wewin will not be responsible for poor quality printing due to poor quality of the upload.</p>
                        <p>Below are all the specifications that the image uploaded will have to adhere to.</p>
                        <ul>
                            <li>Following are the variety of file formats for uploading designs that the Website supports:-
                                <ul>
                                    <li>Bitmap Image (*.bmp)</li>
                                    <li>JPEG Image (*.jpg,*.jpeg)</li>
                                    <li>PNG Image (*.png)</li>
                                </ul>
                            </li>
                            <li>Bleed - The very edges of the document are called the bleed area. To prevent an unwanted white border from showing at the edge of your document, be sure to extend any background colours or design elements all the way to the edge.</li>
                            <li>Trim Marks - Trim lines are the finished size of the document. The document is cut close to the trim line, but because of the mechanical tolerances involved in printing, the actual cut can happen anywhere between the bleeds and the safe margin. Therefore, it is important to keep your text and important images within the safe margin.</li>
                            <li>Safe Area/Margins - The safe margins are borders that are definitely inside the place where the cut will take place. Please remember to keep all important information, like names, addresses, phone numbers or logos within the safe margin (at least .137” from the edge) to ensure that they aren’t cut off when your document is trimmed.</li>
                            <li>Aspect Ratio - The aspect ratio of your image can be determined by dividing the image’s width by its height. If your image’s aspect ratio is not equal to the aspect ratio of our documents, your image may appear stretched or distorted when it is scaled to fit.</li>
                            <li>Resolution - Resolution refers to the number of dots per inch (dpi), or the amount of detail the image has. Most documents prepared for upload should be 300 dpi at 100% of the final print size. Higher resolution means a more detailed image, and also larger file and longer upload time.</li>
                        </ul>
                        <p>You agree that Wewin and ITC are not responsible for any misspellings, errors, or issues in your art file.</p>
                        <p><span>Artwork Approval</span></p>
                        <p>You agree that all artworks for each design are to be approved by You before they get saved. You must evaluate it carefully in the product preview page before saving. Artwork must be checked for spelling, colour, sizes ordered, placement of the art and accuracy of artwork by the User. Wewin and ITC will not accept responsibility for corrections not implemented and/or requested after creation of order number. ITC reserves the right to cancel the order if the image/text is deemed offensive, inappropriate as stated in this document.</p>
                        <p><span>Account Security</span></p>
                        <p>You are solely responsible for the confidentiality of any password and other account information that You create in order to access or use the Website. You agree to notify us immediately on any unauthorized use of your account, user name, or password. You also agree that Wewin and ITC are not liable in any manner for any loss that You may incur as a result of any third party using your password, either with or without your knowledge. You are solely liable for any losses incurred by ITC, its affiliates, officers, directors, employees, consultants, agents, and representatives due to misuse of your account or password.</p>
                        <p>When You establish an account at the Website, You choose a password to help protect your account information. A password is only as strong as You make it: You should select a unique password and keep it safe. You may change the password as often as You wish by going to “My Account” and selecting "Account Update." Wewin and ITC authorize only those persons who need to know personal information to administer your account, to provide or inform You about products and services, or to maintain, improve or administer the Website to access your personal information.</p>
                        <p><span>Payment</span></p>
                        <p>You acknowledge and agree that by placing an order on the Website You are entering into a purchase/sale transaction solely with Wewin. This applies to all cases where the payment is made by all modes i.e. all credit card, bank card, debit card, cheque, bank transfer and other payments are to be made to Wewin. In case of third-party statements including bank and credit card statements the merchant name may appear in an abbreviated format.</p>
                        <p>To place an order You will need to complete the transaction on the Website. This may or may not be assisted with a phone call with the customer service representative. By placing an order on the Website.You are agreeing to the terms and conditions and privacy policy published in the appropriate section of the Website or affiliated websites where specifically referred to such affiliated websites.</p>
                        <p>After You have made your selection and added products to your shopping cart, You will need to proceed to the checkout section. In this section You will be asked for address and other contact information as well as payment related information. Once the payment transaction has been successfully completed your order will be processed on receipt of the funds from the bank or Credit Card Company. Thereafter your products will be shipped once the customisation is complete, order is ready and on completion of logistics operations related to the same.</p>
                        <p>You also agree and acknowledge that the website only facilitates the third-party payment gateway for processing of payments. This facility is managed by the third-party payment gateway provider and You are required to follow all the terms and conditions of such third party payment gateway provider.</p>
                        <p>You are responsible for the accuracy and authenticity of the information provided by You, including the bank account number/credit card details and the like. You agree and acknowledge that Wewin and ITC shall not be liable and in no way be held responsible for any losses whatsoever, whether direct, indirect, incidental or consequential, including without limitation any losses due to delay in processing of payment instruction or any credit card fraud.</p>
                        <p><span>Payment Options</span></p>
                        <p>The following modes of payments are available</p>
                        <ul>
                            <li>Domestic and international credit cards issued by banks and institutions that are part of the Visa &amp; Mastercard Network</li>
                            <li>Visa Debit cards</li>
                            <li>Netbanking/Direct Debit payments from select banks in India. A full list is available at the time of Check Out and prior to making payments for purchases</li>
                        </ul>
                        <p>As prescribed by the financial institutions issuing the credit or debit cards affiliated with Visa and Mastercard You will be required to submit your 16-digit credit card number, card expiry date and 3-digit CVV number (usually on the reverse of the card) when You make your online transaction using your Credit or Debit card. You should also have enrolled your Credit Card with VBV (Verified by Visa) or MSC (Mastercard Secure Code) to complete the transaction.</p>
                        <p><span>Product Pricing</span></p>
                        <p>All prices on this Website are in Indian Rupees. You agree and acknowledge that You shall be responsible for payment of all fees/costs/charges associated with the purchase of products from us and You agree to bear any and all applicable taxes/Goods and Services Tax, cesses etc. levied thereon. However, Wewin shall be responsible to making payment of applicable taxes to the tax authorities. Prices are inclusive of all applicable taxes and exclusive of shipment charges. The final amount that You will pay in your Shopping Cart will always reflect the most recent price inclusive of all taxes and shipment charges.</p>
                        <p>You agree and acknowledge that Wewin and ITC have no jurisdiction on any disputes or, queries, arising out of the payment transaction with respect to failure of transaction or other credit card, debit card or payment frauds etc are not the responsibility of Wewin and ITC. You understand that all disputes with respect to applicable bank charges, failure of transaction, credit card or debit card payment frauds etc. need to be directed to the concerned bank or institution that issued your card or payment instrument.</p>
                        <p><span>Security</span></p>
                        <p>Transactions on the Website are protected by SSL (Secure Sockets Layer) and Secure Data Encryption using a 1024-bit process. Any information You enter when transacting with the Website is sent in a Secure Socket Layer (SSL) session and is encrypted to protect You against unintentional disclosure to third parties. This is an assurance that it follows the best security practices adopted by major online vendors where all payments are processed in real-time for your security and immediate peace of mind. Credit card and Debit card information is not stored by ITC or Wewin and is not taken by ITC or Wewin. This information is taken directly by the payment gateway provider who is authorised and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.</p>
                        <p><span>Out of Stock</span></p>
                        <p>You acknowledge and agree that Wewin and ITC are not responsible for any exercise book size, binding, ruling combination that are out of stock. It is Wewin and ITC’S endeavour to ensure that all products listed on the site are available in stock for dispatch to You.</p>
                        <p><span>Delivery of products</span></p>
                        <p>You acknowledge and agree that purchases are shipped from Wewin’s warehouse in India. You agree and acknowledge that order deliveries will be made by third party courier and logistics companies or postal services and risk in the Products ordered by You will pass to You on the delivery to the third party courier agency of the courier to You. You agree and acknowledge that any once the Product is delivered to You the risk in the Product transfers to You and Wewin shall not be responsible for any defect, damage, loss, destruction occurring to the Products after the delivery of the Products is complete.</p>
                        <p>You agree and acknowledge that any defect, damage, loss, destruction occurring to the Products before the delivery of the Product to You shall lie against Wewin, who will reimburse the entire amount paid at the time of placing the order, to You. You acknowledge that Wewin’s liability lies only up to the amount paid by You at the time of placing the order.</p>
                        <p>You acknowledge and agree that Wewin and ITC are not responsible for any delay in delivery of Products. You may track your order by visiting the ‘Track my order’ section on the Website.</p>
                        <p>You agree and acknowledge that any defect, damage, loss, destruction occurring to the Products before the delivery of the Product to You shall lie against Wewin, who will reimburse the entire amount paid at the time of placing the order, to You. You acknowledge that Wewin’s liability lies only up to the amount paid by You at the time of placing the order.</p>
                        <p>You acknowledge and agree that Wewin and ITC have no responsibility for Products signed by an alternative person other than the person ordering the product at the address indicated at the time of the order. Since the transactions are authorised by You, Wewin and ITC does not take responsibility for incorrect addresses provided at the time of placing the order. You acknowledge and agree that Wewin and ITC are not responsible for any damage caused to the product after delivery.</p>
                        <p>All claims for shortages or manufacturing defect must be reported to customer service on the day of delivery through the contact us page on the website. Also the said shortage of Products or manufacturing defect needs be highlighted and signed on the Proof of delivery copy and returned to the delivery person, or sent back to Wewin on the following address:-</p>
                        <p>Wewin Paper Products, Survey No. 217, Kandlakoya Village, Ayodhya Centre, Medchal Mandal, RR District – 501401, Telangana.</p>
                        <p>Delivery to the address provided by You at the time of checkout, will take place through third party courier service provider. You acknowledge and agree that the timeline suggested on the checkout page is just suggestive and Wewin and ITC shall not be held liable if the delivery doesn’t take place within this timeline.</p>
                        <p>You acknowledge and agree that the third party courier service provider shall try to deliver the product three times at the suggested address. You agree that on non-receipt at the entered shipping address on three occasions, the customised exercise books shall be returned to We. You acknowledge and agree that no refund will be provided to You in such an event. The stock will be held with Wewin for a period of fifteen days on return receipt. You may contact on wewinpaperproducts@gmail.com or at <a href="mailto:customer-support@classmateshop.com">customer-support@classmateshop.com</a> or at toll free number 18004253242 to procure the courier. You agree and acknowledge that You shall bear the courier charges for (a) stock return to Wewin; (b) couriering the stock again to You and (3) any other costs incurred in sending the courier back to You.</p>
                        <p><span>Delivery Charges</span></p>
                        <p>You agree and acknowledge that the shipping and handling charges are included in the price charged to You at the time of checkout while making payments.</p>
                        <p>You agree and acknowledge that the MRP of the product are not inclusive of shipment charges. The final amount that You will pay in your Shopping Cart will always reflect the most recent price inclusive of all taxes and shipment charges.</p>
                        <p>You agree and acknowledge that no cancellations are acceptable after the order has been placed. You agree that once the products are delivered to You and accepted as depicted in the preview at the time of placing the order, there is no refund or exchange possible.</p>
                        <p><span>Return policy</span></p>
                        <p>To return any Products that are damaged or not as per your order specifications, please return these products to the delivery person along with a remark on the delivery challan or dispatch the same to WeWin within 7 days of delivery at the address mentioned in the contact us section of the Website. All damaged Products or Products not as per your order specifications, that are to be returned must be accompanied by a copy of the original receipt, a return / exchange authorization number and in unopened, saleable condition, otherwise the same will not taken back. You agree and acknowledge that postage and charges for return of these will not be refunded. You agree and acknowledge that no offer exchanges or refunds on any sale on any opened or used products will be allowed. Please allow one to three weeks from the day You return your damaged package or an item not as per your order specifications, for your refund request to be processed. You will be contacted once your return is complete.</p>
                        <p><span>User Material</span></p>
                        <p>You may have an opportunity to publish, transmit, submit, or otherwise upload (collectively, “User Material”). As it concerns User Material, without prejudice to your obligation to otherwise comply with applicable laws during the course of using the Services, You agree to hereby comply with any and all applicable laws, as well as any other rules and restrictions that may be set forth herein or on the Website or Services.</p>
                        <p>You agree that ITC shall have the right but have no obligation, to monitor User Material and to restrict or remove User Material that ITC may determine, in its sole discretion, is inappropriate or for any other reason. You acknowledge that ITC reserves the right to investigate and take appropriate legal action against anyone who, in ITC’s sole discretion, violates these Terms, including, but not limited to, terminating their account, terminate, suspend, limit, or use of the Services or access to Content and/or reporting such User Material, conduct, or activity, to law enforcement authorities, in addition to any other available remedies under law or equity. In addition to the restrictions set forth above, You must adhere to the below terms and conditions and not host, display, upload, modify, publish, transmit, update or share any information /material/User Material that:</p>
                        <p>(a) belongs to another person and to which You do not have any right to;</p>
                        <p>(b) is grossly harmful, harassing, blasphemous, hurts the religious sentiments of others, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;</p>
                        <p>(c) harms minors in any way;</p>
                        <p>(d) infringes any patent, trademark, design, copyright or other proprietary rights;</p>
                        <p>(e) violates any law for the time being in force;</p>
                        <p>(f) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
                        <p>(g) impersonates another person;</p>
                        <p>(h) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</p>
                        <p>(i) threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation. You also represent and warrant that the Posting of your User Material does not violate any right of any party, including privacy rights, publicity rights, and intellectual property rights.</p>
                        <p>You acknowledge that the User Material is not confidential and that You have no expectation of privacy in it.</p>
                        <p>In no event does ITC assume any responsibility or liability whatsoever for any User Material, and You agree to waive any legal or equitable rights or remedies You may have against ITC with respect to such User Material.</p>
                        <p>If You have any complaints relating to any third party User Material or Content uploaded on the Website, then please contact: classmate@itc.in your email, which must bear your digital signature or a signed written complaint, should include the following information:</p>
                        <p>Details Of The Objectionable User Material or Content; Details Of The Basis Of The Objection; What Relief Is Being Requested; All Other Relevant Information Required By ITC To Assess The Complaint.</p>
                        <p>ITC shall on examination of the complaint take all reasonable measures, including taking down the objectionable User Material expeditiously in accordance with applicable law. You agree and acknowledge that ITC’s responsibility in relation to objectionable User Material is limited to removing them post receipt of your objections in accordance with these Terms of Use and ITC shall not be responsible or liable for any other damages or losses incurred by You of any nature whatsoever.</p>
                        <p><span>Support</span></p>
                        <p>If You have any questions, complaints or claims with respect to the Website and/or Services, then such correspondence should be directed to the address as given below.</p>
                        <p>ITC Limited</p>
                        <p>Quality Manager, ITC Ltd – ESPB, ITC Centre, 5th Floor, 760, Anna Salai, Chennai - 600002 Please contact us at customer care number 18004253242 or at <a href="mailto:customer-support@classmateshop.com">customer-support@classmateshop.com</a></p>
                        <p>If You have any questions, complaints or claims with respect to the order, dispatch of the Product, then such correspondence should be directed to the address as given below.</p>
                        <p>Wewin Paper Products</p>
                        <p>Survey No. 217, Kandlakoya Village, Ayodhya Centre, Medchal Mandal, RR District – 501401, Telangana.</p>
                        <p>Please contact us at wewinpaperproducts@gmail.com</p>
                        <p><span>Disclaimer of Warranties</span></p>
                        <p><span>Limitation of Liability</span></p>
                        <p>In no case shall ITC, its directors, officers, employees, affiliates, agents, contractors, principals, or licensors be liable for any direct, indirect, incidental, punitive, special, or consequential damages arising from your use of the services or any content or material thereof or for any other claim related in any way to your access of the Website or use of the services or any content or material thereof, including, but not limited to, any errors or omissions in any content or material, or any loss or damage of any kind incurred as a result of the use of the services or any content or material thereof, even if advised of their possibility. Where the laws do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such jurisdictions, ITC’s liability shall be limited to the extent permitted by law.</p>
                        <p><span>Indemnity</span></p>
                        <p>You agree to defend, indemnify and hold harmless ITC and Wewin, and affiliates, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorneys’ fees) arising from: (i) your use of and access to the Services; (ii) your violation of any term of these Terms and Conditions; (iii) your violation of any third party right, including without limitation any publicity, privacy, or intellectual property right; (iv) your breach of any applicable laws; and (v) any unauthorized, improper, illegal or wrongful use of your Account by any person, including a third party, whether or not authorized or permitted by You. This indemnification obligation will survive the expiry or termination of these Terms and Conditions and your use of the Service. Wewin and ITC will notify You promptly of any such claim, loss, liability, or demand, and in addition to your foregoing obligations, You agree to provide us with assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.</p>
                        <p><span>Governing Law and Jurisdiction</span></p>
                        <p>The relationship between You, Wewin and ITC shall be governed by the laws of India without regard to its conflict of law provisions and for resolution of any dispute arising out of your use of the Services. Notwithstanding the foregoing, You agree that (i) ITC and Wewin have the right to bring any proceedings before any court/forum of competent jurisdiction and You irrevocably submit to the jurisdiction of such courts or forum and (ii) any proceeding brought by You shall be exclusively before the courts at Chennai, India.</p>
                        <p>The Products and Services offered on the Website are solely for the purpose of sale in India. Wewin and ITC do not make any representation that the Product(s) and/or the Website is available for use or sale in other locations/ Countries other than India.</p>
                        <p><span>Severability</span></p>
                        <p>If any provision of these Terms and Conditions is held invalid, void, or unenforceable, then that provision shall be considered severable from the remaining provisions, and the remaining provisions given full force and effect.</p>
                        <p><span>Changes</span></p>
                        <p>ITC reserves the right, at any time and from time to time, without notice to You, to update, revise, supplement, and otherwise modify these Terms of Use and to impose new or additional rules, policies, terms, or conditions on your use of the Service. Any material updates, revisions, supplements, modifications, and additional rules, policies, terms, and conditions (collectively referred to in this Terms of Use as “Additional Terms”) will be posted on the Website and will be effective immediately after such posting and thereafter incorporated into these Terms and Conditions . your continued use of the Services will be deemed to constitute your acceptance of any and all such Additional Terms.</p>
                        <p><span>Survival</span></p>
                        <p>You acknowledge that your representations, undertakings, and warranties and the clauses relating to indemnities, limitation of liability, grant of license, governing law, confidentiality shall survive the efflux of time and the termination of these Terms and Conditions.</p>
                        <p><span>Entire Agreement</span></p>
                        <p>These Terms and Conditions and Privacy Policy constitute the entire agreement between You, Wewin and ITC governing your use of the Services, superseding any prior agreements between You, Wewin and ITC regarding such use.</p>
                        <p><span>Coupon Terms &amp; Conditions</span></p>
                        <p> </p>
                        <p><span><span>On Coupon:</span></span>
                        </p>
                        <ol start={1}>
                            <li>The Classmate coupon offer hereinafter referred to as the “Offer” shall be valid for a period mentioned in the communication.</li>
                            <li>Participation in the Offer is purely voluntary. By participating in this Offer, the purchaser is deemed to have accepted these terms and conditions.</li>
                            <li>The Classmate coupon offer hereinafter referred to as the “Offer” shall be valid for a limited period.</li>
                            <li>Participation in the Offer is purely voluntary. By participating in this Offer, the purchaser is deemed to have accepted these terms and conditions.</li>
                        </ol>
                        <ol>
                            <li>The coupon will have designated place for the code. Mostly, the coupon code will be an alphanumerical code.</li>
                            <li>In certain scenarios, after scratching the coupon at the indicated place a unique code will be revealed, the Purchaser needs to enter this unique code while purchasing notebooks at www.classmateshop.com</li>
                        </ol>
                        <ol start={7}>
                            <li>Each code will be valid for a single purchase only</li>
                            <li>To avail the Offer, the Purchaser has to</li>
                        </ol>
                        <p> </p>
                        <ul>
                            <li>Log on to <a href="http://www.classmateshop.com/">www.classmateshop.com</a> website,</li>
                            <li>create an account with the website by filling in the requisite details</li>
                            <li>design your notebook. The Purchasers may design the notebooks using their own material (user material) or the content available on the website www.classmateshop.com.</li>
                            <li>order a minimum order quantity of 6 books,</li>
                            <li>enter the coupon code,</li>
                            <li>make the payment and</li>
                            <li>enter the delivery address.</li>
                        </ul>
                        <p> </p>
                        <ol start={9}>
                            <li>This Offer shall be valid only on notebooks purchased from the website ‘www.classmateshop.com’ and no other source of purchase.</li>
                            <li>This offer is only applicable on the product charge. Meaning, the offer cannot be applied to the shipping &amp; handling charges.</li>
                            <li>This Offer is note available on Classmate notebooks purchase over the counter from retail outlets or other online website except the <a href="http://www.classmateshop.com/">www.classmateshop.com</a> website.</li>
                            <li>By entering the coupon code the Purchasers will get an off on MRP on purchase of Classmate notebooks on <a href="http://www.classmateshop.com/">www.classmateshop.com</a> website.</li>
                            <li>One account holder with <a href="http://www.classmateshop.com/">www.classmateshop.com</a> website is eligible to avail of multiple coupons.</li>
                            <li>The coupon has no monetary value independent of the Offer. The coupon is non-transferable, not- replaceable, non-refundable, non-exchangeable, not for sale or re-sale, cannot be redeemed for cash and cannot be used in conjunction with any other offer.</li>
                            <li>ITC Limited shall not be liable in any manner for any cost or expense incurred by the Purchaser for the purpose of participation in the Offer.</li>
                            <li>This Offer is subject to the availability of the coupons and applicable government regulations.</li>
                            <li>Participating venues reserve the right to vary times and offer availability (e.g. public holidays). </li>
                            <li>ITC Limited will have no legal and financial liability on unclaimed offers, incentives, coupons etc. beyond the applicable period of the promotional offer.</li>
                            <li>The list of participating venues remains subject to change.</li>
                            <li>ITC Limited reserves the right to change the terms and conditions of this Offer without notice, without assigning any reason, at their sole discretion and without any liability.</li>
                            <li>ITC, its officers, directors, employees, agents, successors, or assigns are not liable and do not have obligation with respect to (i) telephone, electronic, hardware, software, network, Internet or computer malfunctions, failures or difficulties including any error in the code, malfunctioning of the code, breakdown of server hosting website or other technical glitch, due to which the Purchaser are unable to avail of the Offer (iii) power-related or weather-related events of any kind, and/or to any event not under ITC Limited’s direct control, (iv) errors, omissions, interruptions, deletions, defects, delays in operation or transmissions, theft, destruction, unauthorized access or alterations by Purchasers or third parties, (vi) any damages or losses of any kind caused to the Purchasers.</li>
                            <li>ITC Limited reserves the right to terminate, modify or extend this Offer, at its absolute discretion, without assigning any reason whatsoever including extending, withdrawing, or discontinuing the same without notice, at its sole and absolute discretion and without any liability.</li>
                            <li>Decision of ITC Limited in all matters relating to this Offer shall be final and binding.</li>
                            <li>ITC Limited shall not be liable for any loss, delay or damage due to the acts of God, governmental actions, other force majeure circumstances and shall not be liable to pay any amount as compensation, or otherwise, for any such loss, delay or damage.</li>
                            <li>Terms and conditions and privacy policy of <a href="http://www.classmateshop.com/">www.classmateshop.com</a> website shall also apply on the purchases made on the website.</li>
                            <li>All disputes relating to this activity shall be subject to the exclusive jurisdiction of the courts at Chennai.</li>
                            <li>No correspondence regarding the Offer shall be entertained.</li>
                        </ol>
                        <p><span>On Contest</span></p>
                        <p>These terms and conditions apply to any CONTEST program for the customers.</p>
                        <ol>
                            <li>The Contest is open only for Indian citizens residing in Indian Territory only.<a href="https://www.classmateshop.com/d2c/default/terms-conditions#_msocom_1">[SM1]</a> <a href="https://www.classmateshop.com/d2c/default/terms-conditions#_msocom_2">[w2]</a> </li>
                            <li>Customers participating or seeking to participate in the contest shall individually be referred to as “Participant” and collectively as “Participants”.</li>
                            <li>Participation in this Contest is purely voluntary. By participating in this Contest, each Participant is deemed to have accepted the complete terms and conditions of this Contest.</li>
                            <li>Incomplete and invalid entries which are not in the format mentioned in these Terms and Conditions will not be accepted.</li>
                            <li>The winners will be selected by ITC. The selection will be on the parameter of creativity of the photograph of the prepared dish.</li>
                            <li>ITC Limited reserves the sole and absolute right to terminate, modify or extend this Contest or make changes to these terms and conditions, at its absolute discretion without notice and without any liability, without assigning any reason whatsoever</li>
                            <li> Participants making statements which are contrary to existing law, bye-laws, public policy or established good practices shall be disqualified from further participating in the contest.</li>
                            <li>The Prize is neither transferable, replaceable nor upgradeable and no cash payment in lieu of the same will be made.</li>
                            <li>Winners would be contacted on their personal numbers or social media accounts. In the event of no response from the participants or the winners, ITC shall not be held responsible for non-delivery of prizes or gifts.</li>
                            <li>ITC Limited reserves the right to not give away the prizes in the event of submission of false, incorrect, misleading or fraudulent information and/or in the event of fraud practices like website or mobile system hacking, etc</li>
                            <li>The prizes will be given to the winner(s) post completion of such audit and verification process as deemed fit by ITC Limited.</li>
                            <li>ITC Limited is not liable to provide warranty or assurance as to the merchantability or fitness of the prizes given. Any issues with any of the prizes are to be taken up directly with the manufacturer.</li>
                            <li>By availing the prizes and/or taking part in the contest, all participants agree that ITC Limited shall be at liberty to use participants’ name &amp; entry and/or photo and/or video that may appear in any advertisements / promotions/media coverage or publicity in any form which exists today or will be known anytime in the future, without any consideration to the Participant and/ or the Winner. No fees or other sums are to be paid to the participants on account of taking part in the aforementioned advertisements / promotions.</li>
                            <li>ITC Limited shall not be liable for any loss due to delay or destruction or damage of prizes/gifts due to Act of God, Governmental actions, riots, loss/damage/delay due to courier services and other force majeure circumstances and shall not be liable to pay any amount as compensation, or damages, for any such loss, delay or damage.</li>
                            <li> ITC Limited, its officers, directors, employees, agents, successors, or assigns are not liable and do not have obligation with respect to(i) notifications, communications or materials sent by a Customer, that are lost, late, misdirected, garbled, inaccurate, incomplete, illegible, unintelligible, damaged or otherwise not received by ITC Limited, in whole or in part, due to computer, post office or technical error of any kind, (ii) telephone, electronic, hardware, software, network, Internet or computer malfunctions, failures or difficulties, (iii) power-related or weather-related events of any kind, and/or to any event not under ITC’s direct control, (iv) entries or other communications from customers that contain inaccurate information or do not comply with these rules, (v) errors, omissions, interruptions, deletions, defects, delays in operation or transmissions, theft, destruction, unauthorized access or alterations by Customer or third parties, (vi) any damages or losses of any kind caused by any gift resulting from acceptance, possession or use of any gift. ITC Limited, in their sole discretion, reserve the right to disqualify any person tampering with the entry process or the operation of the Activity or otherwise violating these rules. ITC Limited further reserves the right to cancel, terminate or modify this Activity if this Activity cannot be completed as planned because of infection by computer virus, bugs, tampering, unauthorized intervention or technical failures of any sort.</li>
                            <li>ITC Limited shall not be responsible for delay in delivery/non-delivery/damage of gifts/prize</li>
                            <li> The activity shall be adjudged by ITC Limited and the decision of ITC Limited will be final and binding with regard to any dispute arising out of this activity and is non-contestable.</li>
                            <li>All disputes relating to this Contest shall be subject to the exclusive jurisdiction of courts at Chennai only.</li>
                            <li>By participating in the contest, the Participants consent to collection, storing, processing and use of personal information and sensitive personal information of the Participants and personal information of their children by ITC Limited and its affiliates.</li>
                            <li>This contest shall be governed by the privacy policy of ITC Limited publish here <a href="https://www.itcportal.com/about-itc/policies/privacy-policy.aspx">https://www.itcportal.com/about-itc/policies/privacy-policy.aspx</a></li>
                        </ol>
                    </div>
                </div>
                    </div>
                </div>

                <DesktopFooter />

                <div id="back-top"  style={{display :'none'}}  onClick={this.topFunction}><a title="Top" href="" >Top</a></div>
            </div>

        )

    }
}

export  default TermsAndCondition
